### ISSUE TITLE
cpuid instruction

### ISSUE THREAD

**Issue by bannsec** [angr/tracer#13]
Ran into a problem when trying to trace a binary today. tracer would always misfollow. Turns out, there is an instruction in there for "cpuid".

Qemu in this example chooses the id of "GenuineIntel" (a reasonable choice).

Angr has the cheeky answer of "Angry CPUID!" (not going to pass any validity checks).

While in general symbolic tracing the question of what to use for cpuid is open (heck, might as well make it symbolic answer?), for concolic tracing in this case it will run the tracer off the qemu tracks.

This seems like an architectural question to me. My 2c are that at the very least it should allow for tracing the same lines as qemu. This could be done by switching the answer to GenuineIntel, making it fully symbolic, etc.

It would also seem reasonable to add a "-cpu" command when running the qemu dynamic tracer to ensure that qemu won't switch up its answer on us.

If it's possible, I'd suggest at least for tracer runs, set the CPU ID statically to "GenuineIntel" and specify the same in QEMU "-cpu coreduo". This makes the most sense to me for concolic tracing of this sort.

[get_started.zip](https://github.com/angr/tracer/files/707048/get_started.zip)

Attaching the problem child binary. Example run is:

```python
import tracer
t = tracer.Tracer("./get_started","A")
t.run()
```

**Comment by ltfish** [comment]
> Angr has the cheeky answer of "Angry CPUID!"

lol...

Take a look at `simuvex/engines/vex/dirty.py`. There we implemented support for CPUID, though we may not be using it by default.

**Comment by rhelmot** [comment]
angr's CPUID output is pretty precisely tuned to claim to be the dumbest processor possible, including the fake identifier. This is because what happens on linux program startup is that the libc initializers use the output of CPUID to determine how to do the rest of initialization - if we claim any more capabilities than baseline, it starts trying to take advantage of them, and tends to run off the rails doing lots of operations on uninitialized data, the source of which I never bothered to track down.

It's very possible these issues have been fixed since then!

I agree wholeheartedly that there should be customization options for CPUID, including a number of presets, cloning your current processor, and symbolic results. How these should be exposed is another question, though a `cpu` state plugin comes to mind.

**Comment by bannsec** [comment]
Wonder if the easy answer for now would be to tell QEMU to return a custom cpuid? That way we could keep to the simpler setup instructions and still track with QEMU. Not sure if QEMU allows this though.

**Comment by rhelmot** [comment]
it does look like qemu can be configured to return specific cpuid flags: `qemu -cpu help` shows them, and then combinations of them can be enabled or disabled on top of a particular profile: `qemu -cpu SandyBridge,-sse /bin/ls` segfaults on my machine, presumably because libc is trying to use an SSE instruction?

**Comment by bannsec** [comment]
Yeah, that makes sense. Unfortunately I don't see a -cpuid="string" type option. I have found references to "cpuid.custom" but it's not clear if that's a user option or a dev option.

**Comment by bannsec** [comment]
So i did a test and swapped in the full sse2 cpuid instruction. It gets past the first call, however it appears the second call (eax == 1) doesn't match. So really, tracer and QEMU would have to fully agree on cpuid for this to work properly.
