### ISSUE TITLE
/dev/shm/tracer-log

### ISSUE THREAD

**Issue by mcgrady1** [angr/tracer#2]
```
Traceback (most recent call last):
  File "tracer_test.py", line 79, in <module>
    **t = tracer.Tracer(program, input)**
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 155, in __init__
    self.trace = self.dynamic_trace()
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 722, in dynamic_trace
    with open(lname, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/dev/shm/tracer-log-jZ87Bt'
```

**Comment by rhelmot** [comment]
Sorry for the slow response. This isn't my code to be providing support for, but I guess someone's gotta do it.

The file that's failing to open is the actual trace log, it is created by a qemu subprocess. The tracer code launches a special build of qemu that has some caching options disabled in order to get an accurate trace. If we can't open it here, it's because qemu failed to write that file there. There are several reasons why this could be:

- tracer was unable to launch qemu
- qemu was unable to write the log file because your system doesn't have a `/dev/shm` (very fast ram-mounted temporary filesystem)
- qemu was unable to execute your binary for some reason

I can't debug this problem for you with the limited information given, so you'll need to debug it on your own. clone the repo and add some print statements to dump out the exact qemu command that gets called, then try running it on your own and see where it dies.

**Comment by wxjia** [comment]
The args of Popen is " ['/usr/bin/x86_64', '-d', 'exec', '-D', '/dev/shm/tracer-log-AnE0Ca', './test1_gcc'] ".
But the command "/usr/bin/x86_64" has no paramter -d.
Can you give us some detail tutorial of DRILLER?
![1](https://cloud.githubusercontent.com/assets/17216009/21471833/8303a31e-cafa-11e6-9153-e8dc214749af.jpg)

**Comment by rhelmot** [comment]
You have installed tracer and shellphish_qemu globally, as root. This is highly not recommended.

We'll fix this eventually, but for now the fix is "use a virtualenv".

**Comment by wxjia** [comment]
But I have no authority when I install "shellphish_qemu" and "tracer " with normal user.

**Comment by salls** [comment]
You should have authority if you use a virtual environment

**Comment by wxjia** [comment]
Could you give us some more detial tutorials and examples of driller?
