### ISSUE TITLE
How to use a file as input instead of stdin

### ISSUE THREAD

**Issue by 1wc** [angr/tracer#59]
Hello, I want to use tracer on an elf, and its input arguments look like [‘./binary’,’./input’]. As you can see, it use a file as input instead of stdin. How can I fix this question? Thinks!

**Comment by rhelmot** [comment]
There is not a convenient interface for it because tracer was designed for CGC binaries, which don't have files. On the angr side, the preconstrainer/state-constructor does support constraining/specifying arbitrary files, it's just not accessible from here, and we don't really have the manpower to add it. Either use the tracer exploration technique manually or tweak the interface here and submit a pull request.
