### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by bannsec** [angr/tracer#9]
Examples would be helpful on tracer. I can think of some basic ones for sure. Would they be best to go under [angr-docs](http://docs.angr.io)?

**Comment by zardus** [comment]
I think so, yeah. Might as well concentrate them there for now.

On Jan 13, 2017 6:30 PM, "Owlz" <notifications@github.com> wrote:

Examples would be helpful on tracer. I can think of some basic ones for
sure. Would they be best to go under angr-docs <http://docs.angr.io>?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angr/tracer/issues/9>, or mute the thread
